# $DomainControllers = (Get-ADDomainController -Filter *).Name 
$array = @()
Foreach ($DomainController in $DomainControllers) { 
    $DomainController
    $Links = Get-ADReplicationConnection -Server $DomainController
    $AutoGenerated = $Links.AutoGenerated 
    $Array += $Links | Where-Object {$_.AutoGenerated -like $false}
} 

$array